import { User } from './user'

export const USERS: User[] = [
    { userName: "edgar123", name: "edgar", lastName: "nunez", email: "edgar@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "admin" },
    { userName: "alexis123", name: "alexis", lastName: "franco", email: "alexis@gmail.com", createdAt: new Date(2021, 2, 2), privilege: "admin" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" },
    { userName: "hector123", name: "hector", lastName: "hernandez", email: "hector@gmail.com", createdAt: new Date(2021, 2, 15), privilege: "user" }
];
